version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: laravel-backend
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:9000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: FitChallenge
      DB_USERNAME: root
      DB_PASSWORD: Thibault0709

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: FitChallenge
      MYSQL_ROOT_PASSWORD: Thibault0709
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Thibault0709

volumes:
  mysql_data:
