version: "3.8"

services:
  backend:
    build:
      context: ./FitChallenge
    container_name: laravel-FitChallenge
    volumes:
      - ./FitChallenge:/var/www
    ports:
      - "8000:9000"
    depends_on:
      - mysql
    working_dir: /var/www
    command: bash -c "composer install && npm install && npm run build && php artisan serve --host=0.0.0.0 --port=9000"

  vite:
    build:
      context: ./FitChallenge
    container_name: vite
    working_dir: /var/www
    volumes:
      - ./FitChallenge:/var/www
      - /var/www/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - backend


  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: FitChallenge
      MYSQL_ROOT_PASSWORD: Thibault0709
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Thibault0709

volumes:
  mysql_data:
