name: Déploiement FitChallenge sur Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Ajouter la clé SSH
        run: |
          echo "${{ secrets.AZURE_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Lancer le script de déploiement
        run: bash deploy.sh
